version: "3.9"

services:
  db:
    image: bitnami/postgresql:16.3.0
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dev-system-db
    volumes:
      - polls_pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/dev-system-db"
      CHOKIDAR_USEPOLLING: true
    command: >
      sh -c "npx prisma generate && npm run dev"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development

volumes:
  polls_pg_data:
